# Generated by Django 3.0.3 on 2020-03-16 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("open", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("mobility", models.FloatField(null=True)),
                ("sheet_resistance", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "unit",
                    models.CharField(choices=[("V", "Volt"), ("A", "Ampere")], max_length=10),
                ),
                ("purpose", models.CharField(max_length=10)),
                (
                    "measurment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="measure.Measurment",
                    ),
                ),
            ],
        ),
    ]
