# Generated by Django 3.0.3 on 2020-03-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurment",
            name="a",
            field=models.FloatField(help_text="y=a*sin(b*t+c)+d", null=True),
        ),
        migrations.AddField(model_name="measurment", name="b", field=models.FloatField(null=True),),
        migrations.AddField(model_name="measurment", name="c", field=models.FloatField(null=True),),
        migrations.AddField(model_name="measurment", name="d", field=models.FloatField(null=True),),
        migrations.AlterField(
            model_name="measurment", name="open", field=models.BooleanField(default=True),
        ),
    ]
