# Generated by Django 3.0.3 on 2020-04-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0005_auto_20200405_1518"),
    ]

    operations = [
        migrations.RenameModel(old_name="Measurment", new_name="Measurement",),
        migrations.RenameField(
            model_name="rhvalue", old_name="measurment", new_name="measurement",
        ),
    ]
