# Generated by Django 3.0.3 on 2020-04-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0008_measurement_steps_per_measurment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="steps_per_measurment",
            new_name="steps_per_measurement",
        ),
    ]
