# Generated by Django 3.0.3 on 2020-04-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0009_auto_20200410_0939"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhvalue",
            name="angle",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
