# Generated by Django 3.0.3 on 2020-04-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0010_rhvalue_angle"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement", name="error", field=models.TextField(default=""),
        ),
    ]
