# Generated by Django 3.0.3 on 2020-04-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0011_measurement_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='description',
        ),
    ]
