# Generated by Django 3.0.3 on 2020-05-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0012_remove_measurement_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement", name="warning", field=models.TextField(default=""),
        ),
    ]
