# Generated by Django 3.0.3 on 2020-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measure", "0013_measurement_warning"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement", name="r12", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="measurement", name="r23", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="measurement", name="r34", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="measurement", name="r41", field=models.FloatField(null=True),
        ),
    ]
